//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.18444
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Fagerhult.Data.Xml {
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.fagerhult.se/fpk", IsNullable=false)]
    public partial class FpkExport {
        
        private MarknadLista marknadListaField;
        
        private SortimentLista sortimentListaField;
        
        private KatalogLista katalogListaField;
        
        private SerieLista serieListaField;
        
        private ProduktLista produktListaField;
        
        private ArtikelLista artikelListaField;
        
        private SprakLista sprakListaField;
        
        private SokOrdGrupp[] sokordGrupperListaField;
        
        private SokOrd[] sokordListaField;
        
        private Symbolbild[] symbolbildListaField;
        
        private ulong dateField;
        
        private string sortimentField;
        
        private string marknadField;
        
        private string uppdeladIMarknaderField;
        
        private string runtimeField;

        private string _FileName;
        
        /// <remarks/>
        public MarknadLista MarknadLista {
            get {
                return this.marknadListaField;
            }
            set {
                this.marknadListaField = value;
            }
        }
        
        /// <remarks/>
        public SortimentLista SortimentLista {
            get {
                return this.sortimentListaField;
            }
            set {
                this.sortimentListaField = value;
            }
        }
        
        /// <remarks/>
        public KatalogLista KatalogLista {
            get {
                return this.katalogListaField;
            }
            set {
                this.katalogListaField = value;
            }
        }
        
        /// <remarks/>
        public SerieLista SerieLista {
            get {
                return this.serieListaField;
            }
            set {
                this.serieListaField = value;
            }
        }
        
        /// <remarks/>
        public ProduktLista ProduktLista {
            get {
                return this.produktListaField;
            }
            set {
                this.produktListaField = value;
            }
        }
        
        /// <remarks/>
        public ArtikelLista ArtikelLista {
            get {
                return this.artikelListaField;
            }
            set {
                this.artikelListaField = value;
            }
        }
        
        /// <remarks/>
        public SprakLista SprakLista {
            get {
                return this.sprakListaField;
            }
            set {
                this.sprakListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SokOrdGrupp", IsNullable=false)]
        public SokOrdGrupp[] SokordGrupperLista {
            get {
                return this.sokordGrupperListaField;
            }
            set {
                this.sokordGrupperListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SokOrd", IsNullable=false)]
        public SokOrd[] SokordLista {
            get {
                return this.sokordListaField;
            }
            set {
                this.sokordListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Symbolbild", IsNullable=false)]
        public Symbolbild[] SymbolbildLista {
            get {
                return this.symbolbildListaField;
            }
            set {
                this.symbolbildListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sortiment {
            get {
                return this.sortimentField;
            }
            set {
                this.sortimentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Marknad {
            get {
                return this.marknadField;
            }
            set {
                this.marknadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UppdeladIMarknader {
            get {
                return this.uppdeladIMarknaderField;
            }
            set {
                this.uppdeladIMarknaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Runtime {
            get {
                return this.runtimeField;
            }
            set {
                this.runtimeField = value;
            }
        }

	    public string FileName
	    {
		    get { return _FileName;}
		    set { _FileName = value;}
	    }


        public static FpkExport Deserialize(string fileName)
        {
            FpkExport productData;

            XmlSerializer s = new XmlSerializer(typeof(FpkExport));

            using (FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read))
            {
                productData = (FpkExport)s.Deserialize(fs);
            }

            productData.FileName = Path.GetFileName(fileName);

            return productData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class MarknadLista {
        
        private Marknad marknadField;
        
        /// <remarks/>
        public Marknad Marknad {
            get {
                return this.marknadField;
            }
            set {
                this.marknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Marknad {
        
        private string namnField;
        
        private string idField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SortimentLista {
        
        private Sortiment[] sortimentField;
        
        private string marknadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sortiment")]
        public Sortiment[] Sortiment {
            get {
                return this.sortimentField;
            }
            set {
                this.sortimentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string marknad {
            get {
                return this.marknadField;
            }
            set {
                this.marknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Sortiment {
        
        private string namnField;
        
        private string beskrivningField;
        
        private SortimentKopplingar sortimentKopplingarField;
        
        private Katalogkopplingar katalogkopplingarField;
        
        private SortimentEgenskap[] egenskapField;
        
        private string idField;
        
        private ushort sprakIdField;
        
        private byte webProduktNrField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        public SortimentKopplingar SortimentKopplingar {
            get {
                return this.sortimentKopplingarField;
            }
            set {
                this.sortimentKopplingarField = value;
            }
        }
        
        /// <remarks/>
        public Katalogkopplingar Katalogkopplingar {
            get {
                return this.katalogkopplingarField;
            }
            set {
                this.katalogkopplingarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Egenskap")]
        public SortimentEgenskap[] Egenskap {
            get {
                return this.egenskapField;
            }
            set {
                this.egenskapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte WebProduktNr {
            get {
                return this.webProduktNrField;
            }
            set {
                this.webProduktNrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SortimentKopplingar {
        
        private string sortimentKopplingField;
        
        /// <remarks/>
        public string SortimentKoppling {
            get {
                return this.sortimentKopplingField;
            }
            set {
                this.sortimentKopplingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Katalogkopplingar {
        
        private string katalogkopplingField;
        
        /// <remarks/>
        public string Katalogkoppling {
            get {
                return this.katalogkopplingField;
            }
            set {
                this.katalogkopplingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SortimentEgenskap {
        
        private string rubrikField;
        
        private string vardeField;
        
        private string typField;
        
        /// <remarks/>
        public string Rubrik {
            get {
                return this.rubrikField;
            }
            set {
                this.rubrikField = value;
            }
        }
        
        /// <remarks/>
        public string Varde {
            get {
                return this.vardeField;
            }
            set {
                this.vardeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class KatalogLista {
        
        private Katalog katalogField;
        
        /// <remarks/>
        public Katalog Katalog {
            get {
                return this.katalogField;
            }
            set {
                this.katalogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Katalog {
        
        private string namnField;
        
        private string beskrivningField;
        
        private string idField;
        
        private ushort sprakIdField;
        
        private byte webKatalogNrField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte WebKatalogNr {
            get {
                return this.webKatalogNrField;
            }
            set {
                this.webKatalogNrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SerieLista {
        
        private Serie[] serieField;
        
        private string marknadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Serie")]
        public Serie[] Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string marknad {
            get {
                return this.marknadField;
            }
            set {
                this.marknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Serie {
        
        private string namnField;
        
        private string beskrivningField;
        
        private SerieEgenskapLista egenskapListaField;
        
        private string[] sortimentKopplingarField;
        
        private string[] marknadKopplingarField;
        
        private SerieDokument[] dokumentListaField;
        
        private string idField;
        
        private ushort sprakIdField;
        
        private ushort webSerieIdField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        public SerieEgenskapLista EgenskapLista {
            get {
                return this.egenskapListaField;
            }
            set {
                this.egenskapListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SortimentKoppling", IsNullable=false)]
        public string[] SortimentKopplingar {
            get {
                return this.sortimentKopplingarField;
            }
            set {
                this.sortimentKopplingarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MarknadKoppling", IsNullable=false)]
        public string[] MarknadKopplingar {
            get {
                return this.marknadKopplingarField;
            }
            set {
                this.marknadKopplingarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dokument", IsNullable=false)]
        public SerieDokument[] DokumentLista {
            get {
                return this.dokumentListaField;
            }
            set {
                this.dokumentListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort WebSerieId {
            get {
                return this.webSerieIdField;
            }
            set {
                this.webSerieIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SerieEgenskapLista {
        
        private SerieEgenskapListaEgenskap egenskapField;
        
        /// <remarks/>
        public SerieEgenskapListaEgenskap Egenskap {
            get {
                return this.egenskapField;
            }
            set {
                this.egenskapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SerieEgenskapListaEgenskap {
        
        private string rubrikField;
        
        private string vardeField;
        
        private string typField;
        
        /// <remarks/>
        public string Rubrik {
            get {
                return this.rubrikField;
            }
            set {
                this.rubrikField = value;
            }
        }
        
        /// <remarks/>
        public string Varde {
            get {
                return this.vardeField;
            }
            set {
                this.vardeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SerieDokument {
        
        private string namnField;
        
        private string beskrivningField;
        
        private string uRIField;
        
        private string typField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class ProduktLista {
        
        private Produkt[] produktField;
        
        private string marknadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Produkt")]
        public Produkt[] Produkt {
            get {
                return this.produktField;
            }
            set {
                this.produktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string marknad {
            get {
                return this.marknadField;
            }
            set {
                this.marknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Produkt {
        
        private string serieKopplingField;
        
        private string namnField;
        
        private ProduktEgenskap[] egenskapListaField;
        
        private ProduktDokument[] dokumentListaField;
        
        private string[] sokordTypKopplingarField;
        
        private string[] symbolbildKopplingarField;
        
        private string idField;
        
        private ushort sprakIdField;
        
        private ushort webProdIdField;
        
        /// <remarks/>
        public string SerieKoppling {
            get {
                return this.serieKopplingField;
            }
            set {
                this.serieKopplingField = value;
            }
        }
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskap", IsNullable=false)]
        public ProduktEgenskap[] EgenskapLista {
            get {
                return this.egenskapListaField;
            }
            set {
                this.egenskapListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dokument", IsNullable=false)]
        public ProduktDokument[] DokumentLista {
            get {
                return this.dokumentListaField;
            }
            set {
                this.dokumentListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SokordTypKoppling", IsNullable=false)]
        public string[] SokordTypKopplingar {
            get {
                return this.sokordTypKopplingarField;
            }
            set {
                this.sokordTypKopplingarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SymbolbildKoppling", IsNullable=false)]
        public string[] SymbolbildKopplingar {
            get {
                return this.symbolbildKopplingarField;
            }
            set {
                this.symbolbildKopplingarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort WebProdId {
            get {
                return this.webProdIdField;
            }
            set {
                this.webProdIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class ProduktEgenskap {
        
        private string rubrikField;
        
        private string vardeField;
        
        private string typField;
        
        /// <remarks/>
        public string Rubrik {
            get {
                return this.rubrikField;
            }
            set {
                this.rubrikField = value;
            }
        }
        
        /// <remarks/>
        public string Varde {
            get {
                return this.vardeField;
            }
            set {
                this.vardeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class ProduktDokument {
        
        private string namnField;
        
        private string beskrivningField;
        
        private string uRIField;
        
        private string typField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class ArtikelLista {
        
        private Artikel[] artikelField;
        
        private string marknadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Artikel")]
        public Artikel[] Artikel {
            get {
                return this.artikelField;
            }
            set {
                this.artikelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string marknad {
            get {
                return this.marknadField;
            }
            set {
                this.marknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Artikel {
        
        private string produktKopplingField;
        
        private string bestnrField;
        
        private ArtikelEgenskap[] egenskapListaField;
        
        private string[] tillbehorsKopplingarField;
        
        private string idField;
        
        private ushort sprakIdField;
        
        /// <remarks/>
        public string ProduktKoppling {
            get {
                return this.produktKopplingField;
            }
            set {
                this.produktKopplingField = value;
            }
        }
        
        /// <remarks/>
        public string Bestnr {
            get {
                return this.bestnrField;
            }
            set {
                this.bestnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskap", IsNullable=false)]
        public ArtikelEgenskap[] EgenskapLista {
            get {
                return this.egenskapListaField;
            }
            set {
                this.egenskapListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TillbehorsKoppling", IsNullable=false)]
        public string[] TillbehorsKopplingar {
            get {
                return this.tillbehorsKopplingarField;
            }
            set {
                this.tillbehorsKopplingarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class ArtikelEgenskap {
        
        private string rubrikField;
        
        private string vardeField;
        
        private byte listSortNrField;
        
        private byte sortNrField;
        
        private string typField;
        
        /// <remarks/>
        public string Rubrik {
            get {
                return this.rubrikField;
            }
            set {
                this.rubrikField = value;
            }
        }
        
        /// <remarks/>
        public string Varde {
            get {
                return this.vardeField;
            }
            set {
                this.vardeField = value;
            }
        }
        
        /// <remarks/>
        public byte ListSortNr {
            get {
                return this.listSortNrField;
            }
            set {
                this.listSortNrField = value;
            }
        }
        
        /// <remarks/>
        public byte SortNr {
            get {
                return this.sortNrField;
            }
            set {
                this.sortNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SprakLista {
        
        private Sprak sprakField;
        
        /// <remarks/>
        public Sprak Sprak {
            get {
                return this.sprakField;
            }
            set {
                this.sprakField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Sprak {
        
        private string namnField;
        
        private string sprakGuidField;
        
        private ushort idField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string SprakGuid {
            get {
                return this.sprakGuidField;
            }
            set {
                this.sprakGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SokOrdGrupp {
        
        private string namnField;
        
        private ushort sprakIdField;
        
        private string sokOrdGruppTypField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SokOrdGruppTyp {
            get {
                return this.sokOrdGruppTypField;
            }
            set {
                this.sokOrdGruppTypField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class SokOrd {
        
        private string namnField;
        
        private ushort sprakIdField;
        
        private string sokOrdTypField;
        
        private string sokOrdGruppIdField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort SprakId {
            get {
                return this.sprakIdField;
            }
            set {
                this.sprakIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SokOrdTyp {
            get {
                return this.sokOrdTypField;
            }
            set {
                this.sokOrdTypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SokOrdGruppId {
            get {
                return this.sokOrdGruppIdField;
            }
            set {
                this.sokOrdGruppIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fagerhult.se/fpk")]
    public partial class Symbolbild {
        
        private string namnField;
        
        private string altTextField;
        
        private string hiResURIField;
        
        private string loResURIField;
        
        private string idField;
        
        private ushort sortNrField;
        
        /// <remarks/>
        public string Namn {
            get {
                return this.namnField;
            }
            set {
                this.namnField = value;
            }
        }
        
        /// <remarks/>
        public string AltText {
            get {
                return this.altTextField;
            }
            set {
                this.altTextField = value;
            }
        }
        
        /// <remarks/>
        public string HiResURI {
            get {
                return this.hiResURIField;
            }
            set {
                this.hiResURIField = value;
            }
        }
        
        /// <remarks/>
        public string LoResURI {
            get {
                return this.loResURIField;
            }
            set {
                this.loResURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort sortNr {
            get {
                return this.sortNrField;
            }
            set {
                this.sortNrField = value;
            }
        }
    }
}
