//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAuthenticate")]
    public interface IAuthenticate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/ValidateKey", ReplyAction="http://tempuri.org/IAuthenticate/ValidateKeyResponse")]
        bool ValidateKey(System.Guid Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/ValidateKey", ReplyAction="http://tempuri.org/IAuthenticate/ValidateKeyResponse")]
        System.Threading.Tasks.Task<bool> ValidateKeyAsync(System.Guid Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/GetUserId", ReplyAction="http://tempuri.org/IAuthenticate/GetUserIdResponse")]
        string GetUserId(System.Guid Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/GetUserId", ReplyAction="http://tempuri.org/IAuthenticate/GetUserIdResponse")]
        System.Threading.Tasks.Task<string> GetUserIdAsync(System.Guid Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/GetUserRoles", ReplyAction="http://tempuri.org/IAuthenticate/GetUserRolesResponse")]
        string[] GetUserRoles(System.Guid Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/GetUserRoles", ReplyAction="http://tempuri.org/IAuthenticate/GetUserRolesResponse")]
        System.Threading.Tasks.Task<string[]> GetUserRolesAsync(System.Guid Ticket);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticateChannel : CommonTests.ServiceReference1.IAuthenticate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateClient : System.ServiceModel.ClientBase<CommonTests.ServiceReference1.IAuthenticate>, CommonTests.ServiceReference1.IAuthenticate {
        
        public AuthenticateClient() {
        }
        
        public AuthenticateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateKey(System.Guid Ticket) {
            return base.Channel.ValidateKey(Ticket);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateKeyAsync(System.Guid Ticket) {
            return base.Channel.ValidateKeyAsync(Ticket);
        }
        
        public string GetUserId(System.Guid Ticket) {
            return base.Channel.GetUserId(Ticket);
        }
        
        public System.Threading.Tasks.Task<string> GetUserIdAsync(System.Guid Ticket) {
            return base.Channel.GetUserIdAsync(Ticket);
        }
        
        public string[] GetUserRoles(System.Guid Ticket) {
            return base.Channel.GetUserRoles(Ticket);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUserRolesAsync(System.Guid Ticket) {
            return base.Channel.GetUserRolesAsync(Ticket);
        }
    }
}
